services:
  core:
    restart: always
    build:
      context: .
    volumes:
      - ".mtproto:/.mtproto"
      - ".env:/.env"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2000M

  ds:
    image: ghcr.io/teadove/fun-datascience:v2.0.3
    restart: always
    environment:
      _UVICORN__HOST: "0.0.0.0"
      _UVICORN__PORT: 8000
      _UVICORN__WORKERS: 2
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 1000M
