version: '3.1'

services:
  redis:
    image: redis:7.2.4-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - "./data/redis:/data"
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 2m
      timeout: 20s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M

  postgres:
    image: postgres:16.3-bookworm
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "main"
      POSTGRES_PASSWORD: "main"
      POSTGRES_DB: "main"
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    labels:
      - "autoheal=true"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "main"]
      interval: 2m
      timeout: 20s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2000M