version: '3.1'

services:
  client:
    restart: always
    environment:
      # https://core.telegram.org/api/obtaining_api_id
      fun_file_storage_path: "/config"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "~/.config/fun-telegram:/config"
      - ".env:/.env"
