version: '3.9'

services:
  core:
    restart: always
    environment:
      fun_file_storage_path: "/config"
      fun_storage__redis_host: "redis"
      fun_storage__mongo_db_url: "mongodb://mongodb:27017"
      fun_storage__clickhouse_url: "clickhouse:9000"
      fun_ds_supplier_url: "http://ds:8000"
    image: ghcr.io/teadove/fun-telegram:v1.11.64
    volumes:
      - ".mtproto:/.mtproto"
      - ".env:/.env"
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
      ds:
        condition: service_healthy
    labels:
      - "autoheal=true"
    healthcheck:
      test: curl -f http://127.0.0.1:3333/health || exit 1
      interval: 2m
      timeout: 20s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1200M

  ds:
    restart: always
    environment:
      _UVICORN__HOST: "0.0.0.0"
      _UVICORN__PORT: 8000
      _UVICORN__WORKERS: 1
    volumes: []
    healthcheck:
      test: curl -f http://127.0.0.1:8000/health || exit 1
      interval: 2m
      timeout: 20s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 1800M
    labels:
      - "autoheal=true"
    image: ghcr.io/teadove/fun-datascience:v2.0.3

  autoheal:
    restart: always
    image: willfarrell/autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M

  redis:
    image: redis:7.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - "./data/redis:/data"
    labels:
      - "autoheal=true"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 2m
      timeout: 20s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M

  postgres:
    image: postgres:16.3-bookworm
    environment:
      POSTGRES_USER: "main"
      POSTGRES_PASSWORD: "main"
      POSTGRES_DB: "main"
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    labels:
      - "autoheal=true"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "main"]
      interval: 2m
      timeout: 20s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2000M
