version: '3.1'

services:
  client:
    restart: always
    environment:
      fun_file_storage_path: "/config"
      fun_storage__redis_host: "redis"
    image: ghcr.io/teadove/fun-telegram:v1.5.2
    volumes:
      - "~/.config/fun-telegram:/config"
      - ".env:/.env"
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - "./data:/data"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

