version: '3.1'

services:
  client:
    restart: always
    environment:
      fun_file_storage_path: "/config"
    image: ghcr.io/teadove/fun-telegram:v1.4.0
    volumes:
      - "~/.config/fun-telegram:/config"
      - ".env:/.env"

  cache:
    image: redis:7.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - "./data:/data"

