version: '3.1'

services:
  client:
    restart: always
    environment:
      fun_file_storage_path: "/config"
    image: ghcr.io/teadove/fun-telegram:v1.3.1
    volumes:
      - "~/.config/fun-telegram:/config"
      - ".env:/.env"
