version: '3.1'

services:
  client:
    restart: always
    environment:
      fun_file_storage_path: "/config"
      fun_storage__redis_host: "redis"
      fun_storage__mongo_db_url: "mongodb://mongodb:27017"
    image: ghcr.io/teadove/fun-telegram:v1.9.5
    volumes:
      - "~/.config/fun-telegram:/config"
      - ".env:/.env"
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  redis:
    image: redis:7.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - "./data:/data"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  mongodb:
    image: mongo:7.0.4-jammy
    environment:
      MONGO_INITDB_DATABASE: db_main
    volumes:
      - "./data/mongo:/data/db"
      - './extra/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
