version: '3.1'

services:
  client:
    restart: always
    environment:
      fun_file_storage_path: "/config"
      fun_storage__redis_host: "redis"
      fun_storage__mongo_db_url: "mongodb://mongodb:27017"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "~/.config/fun-telegram:/config"
      - ".env:/.env"
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    labels:
      - "autoheal=true"
    healthcheck:
      test: curl -f http://127.0.0.1:3333/health || exit 1
      interval: 2m
      timeout: 20s
      retries: 3
      start_period: 5s
      start_interval: 5s

  autoheal:
    restart: always
    image: willfarrell/autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

#  restarter:
#    image: docker:25.0.2-git
#    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]
#    command: [ "/bin/sh", "-c", "while true; sleep 600; docker restart $(docker ps --format '{{.Names}}' | grep 'fun-telegram' | grep 'client'); done" ]
#    restart: unless-stopped
#    depends_on:
#      - client

  redis:
    image: redis:7.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - "./data:/data"
    labels:
      - "autoheal=true"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 2m
      timeout: 20s
      retries: 3
      start_period: 5s
      start_interval: 5s

  mongodb:
    image: mongo:7.0.4-jammy
    environment:
      MONGO_INITDB_DATABASE: db_main
    volumes:
      - "./data/mongo:/data/db"
      - './extra/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro'
    labels:
      - "autoheal=true"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 2m
      timeout: 20s
      retries: 3
      start_period: 5s
      start_interval: 5s
